# Create Infrastructure Pipeline
# Automatically triggered on branch pushes (dev/stage)
trigger:
  branches:
    include:
      - dev
      - stage

variables:
  tf_version: '1.7.5'  # Latest Terraform version

stages:
- stage: Terraform
  displayName: 'Terraform Apply Stage'
  jobs:
  - job: InitPlanApply
    displayName: 'Initialize, Plan, Apply'
    pool:
      vmImage: 'ubuntu-latest'
    steps:

    # Install Terraform
    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: '$(tf_version)'

    # Login to Azure using Service Connection
    - task: AzureCLI@2
      displayName: 'Azure Login'
      inputs:
        azureSubscription: 'terraform-spn'  # Replace with your service connection
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az account show

    # Terraform init
    - script: |
        echo "Switching to environment folder"
        cd environments/$(Build.SourceBranchName)
        terraform init
      displayName: 'Terraform Init'

    # Terraform validate
    - script: |
        cd environments/$(Build.SourceBranchName)
        terraform validate
      displayName: 'Terraform Validate'

    # Terraform plan
    - script: |
        cd environments/$(Build.SourceBranchName)
        terraform plan -out=tfplan -var-file=terraform.tfvars
      displayName: 'Terraform Plan'

    # Terraform apply
    - script: |
        cd environments/$(Build.SourceBranchName)
        terraform apply -auto-approve tfplan
      displayName: 'Terraform Apply'
